### ISSUE TITLE
Ability to change spacing before a comment

### ISSUE THREAD

**Issue by maxdanilov** [looztra/yamkix#11]
Hi there,
Really enjoying your tool, works very well!

One request though would be to be able to set spacing before comments in the output.
Currently, the comments always seem to stay on their previous position, even if actual yaml code has been moved by formatting (because of [ruamel](https://pypi.org/project/ruamel.yaml/) I guess?)

**Example**:
Input file:

```yaml
---
items:
    - part_no:   A4786 # comment
```

Output from yamkix:
```yaml
---
items:
- part_no: A4786       # comment
```

**Feature request:**
I think it should be a tunable parameter, as e.g. [yamllint](https://github.com/adrienverge/yamllint) has a default rule of 2 spaces before a comment.

Example:
```
yamkix --spaces-before-comment 2
```
```yaml
---
items:
- part_no: A4786  # comment
```
