### ISSUE TITLE
Wrong indent for root array

### ISSUE THREAD

**Issue by faceless7171** [looztra/yamkix#12]
Hello,

Thanks for this helpful tool!

If we have root array in the yaml it looks like indent is added to it too.
But I think it should be without any indent.

**Example:**
Input:
```yaml
---
- test1: 
  - test2: test2
```

Output:
```yaml
---
  - test1:
      - test2: test2
```

Expected:
```yaml
---
- test1:
    - test2: test2
```

Thanks in advance!
