### ISSUE TITLE
Properly deal with other comments

### ISSUE THREAD

**Issue by looztra** [looztra/yamkix#31]
For the moment `yamkix` only deals with some types of commands when it has to "move" them from their source position (with `-c`).

Some comments that are not taken into accout :

- file start and end comment (we may want to force them to be at col 0 if that's not the case for instance)
- start and end comments in maps and lists (the question will be : where do we want them positionned?)

```
---
# like that?
a: 1
b:
# Hello
# World
  c: 2
  d: 3
---
# or like that?
a: 1
b:
  # Hello (same col as the first value)
  # World
  c: 2
  d: 3
```

other case : 

```yaml
# before test1 (top level)
test1:
# before test2
  test2:
  # after test2
    test3: 3
```
